#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Asocijacije.Resource", IsApplication=true)]

namespace Asocijacije
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int addWord = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int addWordIn = 2131165185;
			
			// aapt resource value: 0x7f07001c
			public const int btnAddTeam = 2131165212;
			
			// aapt resource value: 0x7f070002
			public const int btnAddWord = 2131165186;
			
			// aapt resource value: 0x7f070017
			public const int btnCancel = 2131165207;
			
			// aapt resource value: 0x7f07001f
			public const int btnCancel2 = 2131165215;
			
			// aapt resource value: 0x7f070005
			public const int btnCancel3 = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int btnNewGame = 2131165197;
			
			// aapt resource value: 0x7f070016
			public const int btnNext = 2131165206;
			
			// aapt resource value: 0x7f07001e
			public const int btnNext2 = 2131165214;
			
			// aapt resource value: 0x7f070004
			public const int btnNext3 = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int btnQuit = 2131165195;
			
			// aapt resource value: 0x7f070019
			public const int btnReturn = 2131165209;
			
			// aapt resource value: 0x7f07000a
			public const int btnSlRec = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int btnrules = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int madeBy = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int naslov = 2131165196;
			
			// aapt resource value: 0x7f070012
			public const int numNum = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int numNumIn = 2131165203;
			
			// aapt resource value: 0x7f07001a
			public const int teamName = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int teamNameIn = 2131165211;
			
			// aapt resource value: 0x7f070010
			public const int teamNum = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int teamNumIn = 2131165201;
			
			// aapt resource value: 0x7f070006
			public const int teamOn = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int teamOnNow = 2131165191;
			
			// aapt resource value: 0x7f07001d
			public const int teamsLeft = 2131165213;
			
			// aapt resource value: 0x7f070018
			public const int textRules = 2131165208;
			
			// aapt resource value: 0x7f070015
			public const int timeIn = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int timeNum = 2131165204;
			
			// aapt resource value: 0x7f070008
			public const int timeOn = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int wordOn = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int wordsLeft = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AddWords = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int GameView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int NewGameView = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int RulesView = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int TeamName = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int applauses = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int chime = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int plucky = 2131034114;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
